# Generated by Django 6.0.4 on 2026-08-24 13:56

import django.db.models.functions.text
from django.db import migrations, models


def normalize_duplicate_product_names(apps, schema_editor):
    Product = apps.get_model('kasir', 'Product')
    used_names = set()
    for product in Product.objects.order_by('id'):
        normalized_name = product.name.casefold()
        if normalized_name not in used_names:
            used_names.add(normalized_name)
            continue

        suffix = 2
        candidate = f'{product.name} ({suffix})'
        while candidate.casefold() in used_names:
            suffix += 1
            candidate = f'{product.name} ({suffix})'
        product.name = candidate
        product.save(update_fields=['name'])
        used_names.add(candidate.casefold())


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_duplicate_product_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_product_name_ci'),
        ),
    ]
