# Generated by Django 6.0.4 on 2026-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_repair_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
    ]
