# Generated by Django 6.0.4 on 2026-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR'), ('transfer', 'Transfer'), ('cancelled', 'Dibatalkan')], default='cash', max_length=20),
        ),
    ]
